version: '3.8'
services:
  mongodb:
    container_name: mongodb-praise
    image: mongo:5.0.6
    env_file:
      - .env
    ports:
      - $MONGO_PORT:27017
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
      - './packages/mongodb/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh:ro'
      - './packages/mongodb/entrypoint.sh:/entrypoint.sh:ro'
    entrypoint: /entrypoint.sh

  api:
    container_name: api-praise
    image: ghcr.io/givepraise/praise/api:latest
    env_file:
      - .env
    restart: always
    ports:
      - $API_PORT:$API_PORT
    volumes:
      - './packages/api/uploads/:/usr/src/uploads/'      
      - './packages/api/exports/:/usr/src/exports/'
    links:
      - mongodb

  discord-bot:
    container_name: discord-bot-praise
    image: ghcr.io/givepraise/praise/discord-bot:latest
    env_file:
      - .env
    restart: always
    links:
      - mongodb

  frontend:
    container_name: frontend-praise
    image: ghcr.io/givepraise/praise/frontend:latest
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    links:
      - api
    command: >
      sh -c "cd /var/www/praise && ./init-env.sh && caddy run --config /etc/caddy/Caddyfile"      

volumes:
  mongodb_data:
  caddy_data:
  caddy_config:
